Aug 27, 2014 2:35:39 PM de.tudarmstadt.ukp.dkpro.core.api.io.ResourceCollectionReaderBase scan(384)
Information: Scanning [file:/home/likewise-open/UKP/reimers/Dropbox/Doktor/DARIAH/dkpro-tutorials/Jython_Tutorial/scripts/examples/example-en.txt]
Aug 27, 2014 2:35:39 PM de.tudarmstadt.ukp.dkpro.core.api.io.ResourceCollectionReaderBase initialize(219)
Information: Found [1] resources to be read
Aug 27, 2014 2:35:40 PM de.tudarmstadt.ukp.dkpro.core.api.resources.internal.ApacheCommonsLoggingAdapter info
Information: :: loading settings :: url = jar:file:/home/likewise-open/UKP/reimers/.jip/cache/org.apache.ivy/ivy/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Aug 27, 2014 2:35:40 PM de.tudarmstadt.ukp.dkpro.core.api.resources.internal.ApacheCommonsLoggingAdapter info
Information: :: loading settings :: url = jar:file:/home/likewise-open/UKP/reimers/.jip/cache/org.apache.ivy/ivy/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Aug 27, 2014 2:35:40 PM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase loadResource
Information: Producing resource from [jar:file:/home/likewise-open/UKP/reimers/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-sentence-en-maxent/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-sentence-en-maxent-20120616.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/sentence-en-maxent.bin] redirected from [jar:file:/home/likewise-open/UKP/reimers/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-model-sentence-en-maxent/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-model-sentence-en-maxent-20120616.1.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/sentence-en-maxent.properties]
Aug 27, 2014 2:35:40 PM de.tudarmstadt.ukp.dkpro.core.api.resources.internal.ApacheCommonsLoggingAdapter info
Information: :: loading settings :: url = jar:file:/home/likewise-open/UKP/reimers/.jip/cache/org.apache.ivy/ivy/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Aug 27, 2014 2:35:40 PM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase loadResource
Information: Producing resource from [jar:file:/home/likewise-open/UKP/reimers/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-token-en-maxent/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-token-en-maxent-20120616.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/token-en-maxent.bin] redirected from [jar:file:/home/likewise-open/UKP/reimers/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-model-token-en-maxent/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-model-token-en-maxent-20120616.1.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/token-en-maxent.properties]
Aug 27, 2014 2:35:40 PM de.tudarmstadt.ukp.dkpro.core.api.resources.internal.ApacheCommonsLoggingAdapter info
Information: :: loading settings :: url = jar:file:/home/likewise-open/UKP/reimers/.jip/cache/org.apache.ivy/ivy/ivy-2.3.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Aug 27, 2014 2:35:40 PM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase loadResource
Information: Producing resource from jar:file:/home/likewise-open/UKP/reimers/.ivy2/cache/de.tudarmstadt.ukp.dkpro.core/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-chunker-en-default/jars/de.tudarmstadt.ukp.dkpro.core.opennlp-upstream-chunker-en-default-20100908.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/chunker-en-default.bin
Aug 27, 2014 2:35:40 PM org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl callAnalysisComponentProcess(417)
Schwerwiegend: Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.    
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:401)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:309)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:569)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:411)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:266)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:267)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:280)
	at org.apache.uima.fit.pipeline.JCasIterator.next(JCasIterator.java:139)
	at org.apache.uima.fit.pipeline.JCasIterator.next(JCasIterator.java:48)
	at org.python.core.PyJavaType$IteratorIter.__iternext__(PyJavaType.java:880)
	at org.python.pycode._pyx0.f$0(chunking.jy:55)
	at org.python.pycode._pyx0.call_function(chunking.jy)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1312)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:235)
	at org.python.util.jython.run(jython.java:334)
	at org.python.util.jython.main(jython.java:145)
Caused by: java.lang.IllegalStateException: Every token must have a POS tag.
	at de.tudarmstadt.ukp.dkpro.core.opennlp.OpenNlpChunker.process(OpenNlpChunker.java:187)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	... 18 more

Aug 27, 2014 2:35:40 PM org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl processAndOutputNewCASes(274)
Schwerwiegend: Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.    
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:401)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:309)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:569)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:411)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:266)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:267)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:280)
	at org.apache.uima.fit.pipeline.JCasIterator.next(JCasIterator.java:139)
	at org.apache.uima.fit.pipeline.JCasIterator.next(JCasIterator.java:48)
	at org.python.core.PyJavaType$IteratorIter.__iternext__(PyJavaType.java:880)
	at org.python.pycode._pyx0.f$0(chunking.jy:55)
	at org.python.pycode._pyx0.call_function(chunking.jy)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1312)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:235)
	at org.python.util.jython.run(jython.java:334)
	at org.python.util.jython.main(jython.java:145)
Caused by: java.lang.IllegalStateException: Every token must have a POS tag.
	at de.tudarmstadt.ukp.dkpro.core.opennlp.OpenNlpChunker.process(OpenNlpChunker.java:187)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	... 18 more

Traceback (most recent call last):
  File "chunking.jy", line 55, in <module>
    for jcas in pipeline:
java.lang.IllegalStateException: org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.    
	at org.apache.uima.fit.pipeline.JCasIterator.next(JCasIterator.java:160)
	at org.apache.uima.fit.pipeline.JCasIterator.next(JCasIterator.java:48)
	at org.python.core.PyJavaType$IteratorIter.__iternext__(PyJavaType.java:880)
	at org.python.pycode._pyx0.f$0(chunking.jy:55)
	at org.python.pycode._pyx0.call_function(chunking.jy)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1312)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:235)
	at org.python.util.jython.run(jython.java:334)
	at org.python.util.jython.main(jython.java:145)
Caused by: org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.    
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:401)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:309)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:569)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:411)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:266)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:267)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:280)
	at org.apache.uima.fit.pipeline.JCasIterator.next(JCasIterator.java:139)
	... 10 more
Caused by: java.lang.IllegalStateException: Every token must have a POS tag.
	at de.tudarmstadt.ukp.dkpro.core.opennlp.OpenNlpChunker.process(OpenNlpChunker.java:187)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	... 18 more

java.lang.IllegalStateException: java.lang.IllegalStateException: org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.    
